services:
  
  financeye-mysql:
    image: mysql:8.0
    container_name: financeye_db
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=financeye
      - MYSQL_DATABASE=financeye
      - MYSQL_USER=lucasraiony
      - MYSQL_PASSWORD=lucasraiony
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    container_name: financeye-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  financeye-php-fpm:
      build: .
      image: financeye_php_fpm:latest
      container_name: financeye
      working_dir: /application
      volumes:
        - .:/application